name: Run tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Run Autowriter.Core.Tests
      run: dotnet test ./Autowriter.Core.Tests/Autowriter.Core.Tests.csproj
    - name: Run Autowriter.RazorPages.Tests
      run: dotnet test --blame-hang --blame-hang-timeout 10sec ./Autowriter.RazorPages.Tests/Autowriter.RazorPages.Tests.csproj
