name: Run tests

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Debug Autowriter.sln
    - name: Run core tests
      run: dotnet test --no-restore Autowriter.Core.Tests\Autowriter.Core.Tests.csproj
    - name: Run RazorPages tests
      run: dotnet test --no-restore Autowriter.RazorPages.Tests\Autowriter.RazorPages.csproj
